# YAML Lint Configuration
---
extends: default

rules:
  line-length:
    max: 120
    level: warning

  indentation:
    spaces: 2
    indent-sequences: consistent

  comments:
    min-spaces-from-content: 1

  comments-indentation: {}

  document-start: disable

  truthy:
    allowed-values: ['true', 'false', 'yes', 'no']
    check-keys: false

  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0

  colons:
    max-spaces-before: 0
    max-spaces-after: 1

  commas:
    max-spaces-before: 0
    min-spaces-after: 1
    max-spaces-after: 1

  empty-lines:
    max: 2

  key-duplicates: {}

  new-line-at-end-of-file: {}

  trailing-spaces: {}

ignore: |
  .venv/
  venv/
  node_modules/
  .git/
  .mypy_cache/
  .pytest_cache/
